<?php

namespace Database\Seeders;

use App\Models\Position;
use App\Models\PositionRate;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PositionRateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['position' => 'Quality Control Leader', 'rate' => 51923],
            ['position' => 'Quality Control Craft', 'rate' => 50052],
            ['position' => 'Quality Control Senior', 'rate' => 49450],
            ['position' => 'Quality Control Junior', 'rate' => 46010],
            ['position' => 'Dimensional Control Leader', 'rate' => 51546],
            ['position' => 'Dimensional Control Craft', 'rate' => 49719],
            ['position' => 'Dimensional Control Senior', 'rate' => 49558],
            ['position' => 'Dimensional Control Junior', 'rate' => 45365],
            ['position' => 'Draftter Leader', 'rate' => 51923],
            ['position' => 'Draftter Craft', 'rate' => 50579],
            ['position' => 'Draftter Senior', 'rate' => 49450],
            ['position' => 'Draftter Junior', 'rate' => 46064],
            ['position' => 'Document Control Leader', 'rate' => 49896],
            ['position' => 'Document Control Craft', 'rate' => 49082],
            ['position' => 'Document Control Senior', 'rate' => 48940],
            ['position' => 'Document Control Junior', 'rate' => 44781],
            ['position' => 'Material Take Off Leader', 'rate' => 51546],
            ['position' => 'Material Take Off Craft', 'rate' => 49719],
            ['position' => 'Material Take Off Senior', 'rate' => 49166],
            ['position' => 'Material Take Off Junior', 'rate' => 45311],
            ['position' => 'HR Leader', 'rate' => 51546],
            ['position' => 'HR Craft', 'rate' => 49719],
            ['position' => 'HR Senior', 'rate' => 49558],
            ['position' => 'HR Junior', 'rate' => 45311],
            ['position' => 'IT Leader', 'rate' => 51976],
            ['position' => 'IT Craft', 'rate' => 50525],
            ['position' => 'IT Senior', 'rate' => 50418],
            ['position' => 'IT Junior', 'rate' => 46064],
            ['position' => 'Traveller Leader', 'rate' => 50872],
            ['position' => 'Traveller Craft', 'rate' => 49082],
            ['position' => 'Traveller Senior', 'rate' => 48940],
            ['position' => 'Traveller Junior', 'rate' => 44781],
            ['position' => 'HSE Leader', 'rate' => 51923],
            ['position' => 'HSE Craft', 'rate' => 50525],
            ['position' => 'HSE Senior', 'rate' => 49450],
            ['position' => 'HSE Junior', 'rate' => 46064],
            ['position' => 'Warehouseman Leader', 'rate' => 50416],
            ['position' => 'Warehouseman Craft', 'rate' => 48976],
            ['position' => 'Warehouseman Senior', 'rate' => 48888],
            ['position' => 'Warehouseman Junior', 'rate' => 44674],
            ['position' => 'Structural Fitter Leader', 'rate' => 50330],
            ['position' => 'Structural Fitter Craft', 'rate' => 50508],
            ['position' => 'Structural Fitter Senior', 'rate' => 48737],
            ['position' => 'Structural Fitter Junior', 'rate' => 44968],
            ['position' => 'Structural Welder Leader', 'rate' => 59568],
            ['position' => 'Structural Welder SMAW 3G-4G', 'rate' => 50047],
            ['position' => 'Structural Welder SMAW 6G', 'rate' => 54210],
            ['position' => 'Structural Welder SMAW 6G-GR', 'rate' => 55238],
            ['position' => 'Structural Welder FCAW GS 3G-4G', 'rate' => 51095],
            ['position' => 'Structural Welder FCAW GS 6G', 'rate' => 55238],
            ['position' => 'Structural Welder FCAW SS 3G-4G', 'rate' => 51095],
            ['position' => 'Structural Welder FCAW SS 6GR', 'rate' => 56276],
            ['position' => 'Structural Welder SAW 1G', 'rate' => 50047],
            ['position' => 'Structural Welder GMAW 5G', 'rate' => 51261],
            ['position' => 'Structural Welder PWHT', 'rate' => 52133],
            ['position' => 'Structural Welder Monitor', 'rate' => 48662],
            ['position' => 'Rigger Leader', 'rate' => 48681],
            ['position' => 'Rigger Craft', 'rate' => 48845],
            ['position' => 'Rigger Senior', 'rate' => 47674],
            ['position' => 'Rigger Junior', 'rate' => 44775],
            ['position' => 'Pipe Fitter Leader', 'rate' => 50413],
            ['position' => 'Pipe Fitter Craft', 'rate' => 50585],
            ['position' => 'Pipe Fitter Senior', 'rate' => 49268],
            ['position' => 'Pipe Fitter Junior', 'rate' => 48053],
            ['position' => 'Pipe Welder Leader', 'rate' => 71761],
            ['position' => 'Pipe Welder SMAW/GTAW 6G', 'rate' => 55238],
            ['position' => 'Pipe Welder GTAW 6G', 'rate' => 54210],
            ['position' => 'Pipe Welder SMAW/GTAW SS 6G', 'rate' => 56276],
            ['position' => 'Pipe Welder SMAW/GTAW Alloy 6G', 'rate' => 68825],
            ['position' => 'Pipe Welder SMAW/GTAW Duplex 6G', 'rate' => 65626],
            ['position' => 'Pipe Welder PWHT', 'rate' => 53162],
            ['position' => 'Pipe Welder Monitor', 'rate' => 49042],
            ['position' => 'Blaster Painter Leader', 'rate' => 48480],
            ['position' => 'Blaster Painter Craft', 'rate' => 48845],
            ['position' => 'Blaster Painter Senior', 'rate' => 47716],
            ['position' => 'Blaster Painter Junior', 'rate' => 44787],
            ['position' => 'Mechanical Fitter Leader', 'rate' => 50286],
            ['position' => 'Mechanical Fitter Craft', 'rate' => 50204],
            ['position' => 'Mechanical Fitter Senior', 'rate' => 48402],
            ['position' => 'Mechanical Fitter Junior', 'rate' => 45460],
            ['position' => 'Electrician Leader', 'rate' => 49854],
            ['position' => 'Electrician Craft', 'rate' => 50022],
            ['position' => 'Electrician Senior', 'rate' => 48204],
            ['position' => 'Electrician Junior', 'rate' => 45485],
            ['position' => 'Instrument Fitter Leader', 'rate' => 50471],
            ['position' => 'Instrument Fitter Craft', 'rate' => 49256],
            ['position' => 'Instrument Fitter Senior', 'rate' => 48513],
            ['position' => 'Instrument Fitter Junior', 'rate' => 46064],
            ['position' => 'Technician Leader', 'rate' => 50106],
            ['position' => 'Technician Craft', 'rate' => 50022],
            ['position' => 'Technician Senior', 'rate' => 48204],
            ['position' => 'Technician Junior', 'rate' => 45485],
            ['position' => 'Scaffolder Leader', 'rate' => 48974],
            ['position' => 'Scaffolder Craft', 'rate' => 49344],
            ['position' => 'Scaffolder Senior', 'rate' => 47674],
            ['position' => 'Scaffolder Junior', 'rate' => 44787],
            ['position' => 'Operator Leader', 'rate' => 50106],
            ['position' => 'Operator Craft', 'rate' => 49511],
            ['position' => 'Operator Senior', 'rate' => 47716],
            ['position' => 'Operator Junior', 'rate' => 45011],
            ['position' => 'Administrator Leader', 'rate' => 54007],
            ['position' => 'Administrator Craft', 'rate' => 50967],
            ['position' => 'Administrator Senior', 'rate' => 50795],
            ['position' => 'Administrator Junior', 'rate' => 46150],
            ['position' => 'Janitor Leader', 'rate' => 52353],
            ['position' => 'Janitor Craft', 'rate' => 50967],
            ['position' => 'Janitor Senior', 'rate' => 50795],
            ['position' => 'Janitor Junior', 'rate' => 46150],
            ['position' => 'Nurse', 'rate' => 50709],
            ['position' => 'Associate Quality Inspector', 'rate' => 1201863],
            ['position' => 'Pipe Fitter Supervisor', 'rate' => 1627049],
            ['position' => 'Junior Nurse', 'rate' => 52729],
            ['position' => 'Doctor', 'rate' => 906808],
            ['position' => 'Cable Puller/ Electrician Junior', 'rate' => 45485],
            ['position' => 'Laborer/ Janitor Junior', 'rate' => 46150],
        ];
        
        PositionRate::insert($data);
        
    }
}
